src/main/java/io/airlift/compress/snappy/CorruptionException.java, src/main/java/io/airlift/compress/snappy/Snappy.java, src/main/java/io/airlift/compress/snappy/SnappyDecompressor.java
To be replaced with MalformedInputException later
=> Move CorruptionException to snappy package

pom.xml, src/test/java/io/airlift/compress/AbstractTestCompression.java, src/test/java/io/airlift/compress/TestingModule.java, src/test/java/io/airlift/compress/benchmark/DataSet.java
They were being loaded once per test and TestNG was holding on to all instances
until the very end, which resulted in OOMs.
=> Load and instantiate test data sets once per VM

src/main/java/io/airlift/compress/lzo/LzoRawCompressor.java
LZO has a special encoding for small copies with small offset. This
command has a shorter encoding than the standard command. This change
makes the compression ratio comparable to LZO and LZ4.
=> Use LZO short copy command when possible

src/main/java/io/airlift/compress/lz4/Lz4Codec.java, src/main/java/io/airlift/compress/lzo/LzoCodec.java, src/main/java/io/airlift/compress/snappy/SnappyCodec.java
Some Hadoop code will cache codec instances, and when the instance
is returned to the pool, the reset method is called. Aircompressor
codecs do not have internal state so the reset method does nothing.
=> All Hadoop codec to be reset

src/main/java/io/airlift/compress/lz4/Lz4Compressor.java, src/main/java/io/airlift/compress/lz4/Lz4RawCompressor.java, src/main/java/io/airlift/compress/lzo/LzoCompressor.java, src/main/java/io/airlift/compress/lzo/LzoRawCompressor.java
Before:
```
compress    airlift_lz4             silesia/dickens              6,366,945   253.2MB/s ±  8201.4kB/s ( 3.16%) (N = 30, α = 99.9%)
compress    airlift_lz4             silesia/mozilla             26,435,667   411.5MB/s ±  8480.2kB/s ( 2.01%) (N = 30, α = 99.9%)
compress    airlift_lz4             silesia/mr                   5,440,937   382.1MB/s ±    16.0MB/s ( 4.20%) (N = 30, α = 99.9%)
compress    airlift_lz4             silesia/nci                  5,533,040   721.4MB/s ±    27.3MB/s ( 3.78%) (N = 30, α = 99.9%)
compress    airlift_lz4             silesia/ooffice              4,338,918   318.9MB/s ±  9512.4kB/s ( 2.91%) (N = 30, α = 99.9%)
compress    airlift_lz4             silesia/osdb                 5,256,666   355.4MB/s ±    10.3MB/s ( 2.89%) (N = 30, α = 99.9%) …
```
=> Improve LZO & LZ4 compression performance for small inputs

src/main/java/io/airlift/compress/zstd/FseTableReader.java
The code was incorrectly comparing with < instead of <=
=> Fix off-by-one error when reading FSE table

src/test/java/io/airlift/compress/benchmark/CompressionBenchmark.java
With this, it is possible to run a benchmark for a specific dataset or algorithm via:
```
mvn exec:exec \
-Dexec.classpathScope=test \
-Dexec.executable="java" \
-Dexec.args="-cp %classpath io.airlift.compress.benchmark.CompressionBenchmark -p name=XXXX -p algorithm=YYYY"
```
=> Allow overriding benchmark parameters from command line

src/main/java/io/airlift/compress/lz4/Lz4RawCompressor.java, src/test/java/io/airlift/compress/lz4/BenchmarkCount.java
Using a counted loop improves performance, especially for long matches
```
Benchmark (matchLength)  (padding)  Mode  Cnt   Score   Error  Units
before                1          0  avgt   30   4.452 ± 0.074  ns/op
after                 1          0  avgt   30   4.450 ± 0.292  ns/op
before                1          1  avgt   30   4.438 ± 0.069  ns/op
after                 1          1  avgt   30   4.178 ± 0.097  ns/op
before                1          3  avgt   30   4.600 ± 0.111  ns/op
after                 1          3  avgt   30   4.231 ± 0.162  ns/op
before                1          7  avgt   30   4.276 ± 0.089  ns/op
after                 1          7  avgt   30   3.863 ± 0.065  ns/op
before                1         50  avgt   30   4.302 ± 0.093  ns/op
after                 1         50 …
```
=> Optimize match length count function

pom.xml, src/main/java/io/airlift/compress/snappy/SnappyRawCompressor.java, src/test/java/io/airlift/compress/benchmark/Algorithm.java, src/test/java/io/airlift/compress/benchmark/CompressionBenchmark.java, src/test/java/io/airlift/compress/lz4/TestLz4.java, src/test/java/io/airlift/compress/thirdparty/JPountzLz4Compressor.java, src/test/java/io/airlift/compress/thirdparty/JPountzLz4Decompressor.java, src/test/java/io/airlift/compress/thirdparty/XerialSnappyCompressor.java, src/test/java/io/airlift/compress/thirdparty/XerialSnappyDecompressor.java, src/test/java/io/airlift/compress/thirdparty/ZstdJniCompressor.java, src/test/java/io/airlift/compress/thirdparty/ZstdJniDecompressor.java
The latest versions have received many improvements and perform much better in benchmarks. They also implement more of the APIs being evaluated.
=> Update compression libraries to latest versions

pom.xml
In my local, unscientific benchmark, the new version of zstd-jni generally performs better than the older version. The project has indicated several improvements have been made.
=> Update zstd-jni to latest versions

pom.xml, src/test/java/io/airlift/compress/HadoopNative.java
Use the updated version from Trino. Among other things, it
fixes a bug when running tests in newer versions of the JDK.
=> Update hadoop-apache dependency

src/main/java/io/airlift/compress/lz4/UnsafeUtil.java, src/main/java/io/airlift/compress/lzo/UnsafeUtil.java, src/main/java/io/airlift/compress/snappy/UnsafeUtil.java, src/main/java/io/airlift/compress/zstd/UnsafeUtil.java
Java 16 removed reflective access to internal fields in the java.nio.Buffer class
to be able to operate on direct byte buffers, so resort to Unsafe as a stop gap.
We'll revisit this later, possibly when the Foreign-Memory Access API
becomes final.
Fixes #125
=> Use Unsafe to obtain location of direct Buffer address field

.github/workflows/main.yml, pom.xml, src/main/java/io/airlift/compress/lz4/Lz4Compressor.java, src/main/java/io/airlift/compress/lz4/Lz4Decompressor.java, src/main/java/io/airlift/compress/lzo/LzoCompressor.java, src/main/java/io/airlift/compress/lzo/LzoDecompressor.java, src/main/java/io/airlift/compress/snappy/SnappyCompressor.java, src/main/java/io/airlift/compress/snappy/SnappyDecompressor.java, src/main/java/io/airlift/compress/zstd/ZstdCompressor.java, src/main/java/io/airlift/compress/zstd/ZstdDecompressor.java, src/test/java/io/airlift/compress/AbstractTestCompression.java
Fixes https://github.com/airlift/aircompressor/issues/133
=> Properly target Java 8

pom.xml, src/main/java/io/airlift/compress/lz4/Lz4Compressor.java, src/main/java/io/airlift/compress/lz4/Lz4Decompressor.java, src/main/java/io/airlift/compress/lzo/LzoCompressor.java, src/main/java/io/airlift/compress/lzo/LzoDecompressor.java, src/main/java/io/airlift/compress/snappy/SnappyCompressor.java, src/main/java/io/airlift/compress/snappy/SnappyDecompressor.java, src/main/java/io/airlift/compress/zstd/ZstdCompressor.java, src/main/java/io/airlift/compress/zstd/ZstdDecompressor.java, src/test/java/io/airlift/compress/AbstractTestCompression.java, src/test/java/io/airlift/compress/zstd/TestZstd.java
Extracted from https://github.com/airlift/aircompressor/pull/142
=> Prevent JVM crash when buffer too small

src/main/java/io/airlift/compress/zstd/Util.java, src/main/java/io/airlift/compress/zstd/ZstdFrameDecompressor.java, src/test/java/io/airlift/compress/zstd/TestUtil.java, src/test/java/io/airlift/compress/zstd/TestZstd.java
Fixes an issue where the existing zstd decompressor can make an out-of-bounds unsafe read.
Currently the line
```java
verify(input + SIZE_OF_BLOCK_HEADER <= inputLimit, input, "Not enough input bytes");
```
won't catch out-of-bounds reads because it only checks for `SIZE_OF_BLOCK_HEADER`, even tho the code reads a full int.
We fix this by reading only the bytes we care about. I've mirrored the existing `put24BitLittleEndian` function with a new `get24BitLittleEndian` and added a few tests.
=> Fix 24 bit out-of-bounds read

src/main/java/io/airlift/compress/zstd/ZstdDecompressor.java
I have run a bunch of performance benchmarks. The ZSTD.decompress method with byte arrays was a lot faster than the ZSTD decompress with ByteBuffers. 
It's because the ByteBuffer implementation allocates another ZSTD Frame Decompressor every time it decompresses.
This PR uses the already existing ZSTDFrameDecompressor instead of allocating a new one for every decompression.
=> Improve ZSTD decomompress byte buffer performance

src/main/java/io/airlift/compress/zstd/BlockCompressionState.java, src/main/java/io/airlift/compress/zstd/CompressionContext.java, src/main/java/io/airlift/compress/zstd/CompressionParameters.java, src/main/java/io/airlift/compress/zstd/FrameHeader.java, src/main/java/io/airlift/compress/zstd/Util.java, src/main/java/io/airlift/compress/zstd/XxHash64.java, src/main/java/io/airlift/compress/zstd/ZstdCodec.java, src/main/java/io/airlift/compress/zstd/ZstdFrameCompressor.java, src/main/java/io/airlift/compress/zstd/ZstdFrameDecompressor.java, src/main/java/io/airlift/compress/zstd/ZstdHadoopInputStream.java, src/main/java/io/airlift/compress/zstd/ZstdHadoopOutputStream.java, src/main/java/io/airlift/compress/zstd/ZstdHadoopStreams.java, src/main/java/io/airlift/compress/zstd/ZstdIncrementalFrameDecompressor.java, src/main/java/io/airlift/compress/zstd/ZstdInputStream.java, src/main/java/io/airlift/compress/zstd/ZstdOutputStream.java, src/test/java/io/airlift/compress/zstd/TestZstd.java, src/test/java/io/airlift/compress/zstd/TestZstdCodec.java, src/test/java/io/airlift/compress/zstd/TestZstdCodecByteAtATime.java, src/test/java/io/airlift/compress/zstd/TestZstdPartial.java, src/test/java/io/airlift/compress/zstd/TestZstdStream.java, src/test/java/io/airlift/compress/zstd/ZstdPartialDecompressor.java, src/test/java/io/airlift/compress/zstd/ZstdStreamCompressor.java, src/test/java/io/airlift/compress/zstd/ZstdStreamDecompressor.java
=> Zstd streaming and Hadoop Codec

src/main/java/io/airlift/compress/zstd/ZstdOutputStream.java, src/test/java/io/airlift/compress/zstd/ZstdStreamCompressor.java
In some cases, the ZSTD output stream is flushed before growing the buffer to the maximum size.  This can cause an exception when sliding the output window, and can also hurt performance as the window is copied more often.
=> Fix ZSTD output stream failure when buffer is flushed early

src/main/java/io/airlift/compress/zstd/ZstdOutputStream.java
ZstdOutputStream will write out the last chunk every time close() is invoked on it, which can cause errors when the output is later decompressed. Per the java.io.Closeable interface documentation, the close() method should have no effect if invoked on an already-closed stream (which is how e.g. the core DeflaterOutputStream behaves as well), so make it a noop if the stream was already closed.
=> Fix ZstdOutputStream corruption on double close

src/main/java/io/airlift/compress/snappy/SnappyRawDecompressor.java
In the slow literal copy path, it wasn't validating that the literal fit within the input buffer, so the call to copyMemory could read from out of bounds and cause a crash.
When copying a match, it wasn't validating that the match fit within the output buffer in both branches (slow & fast path), so the operation could write outside of the output buffer if the match length was corrupted.
Fixes #183
=> Fix out of bounds read/write in Snappy decompressor

src/main/java/io/airlift/compress/lz4/Lz4RawDecompressor.java, src/main/java/io/airlift/compress/lzo/LzoRawDecompressor.java, src/main/java/io/airlift/compress/snappy/SnappyRawDecompressor.java, src/main/java/io/airlift/compress/zstd/Huffman.java, src/main/java/io/airlift/compress/zstd/ZstdFrameDecompressor.java, src/test/java/io/airlift/compress/lz4/TestLz4.java, src/test/java/io/airlift/compress/lzo/TestLzo.java, src/test/java/io/airlift/compress/snappy/TestSnappy.java, src/test/java/io/airlift/compress/zstd/TestZstd.java
If the computed literal length was greater than Integer.MAX_VALUE, the value would overflow to a negative and cause a read before the beginning of the buffer.
Fix other assorted missing bounds checks.
=> Fix out of bounds read/writes

src/main/java/io/airlift/compress/v2/internal/NativeLoader.java
java.io.tmpdir is meant to be the default path if aircompressor.tmpdir is not specified. The parentheses were misplaced.
=> Fix temp path construction

pom.xml
The new APIs were accidently released with the old Maven artifact-id. To avoid problems with services like Github Dependabot, we are advancing the existing 0.xx version to 2.0.1 and the new APIs will be v3.
=> Update to version 2.0.1

src/main/java/io/airlift/compress/v3/Compressor.java, src/main/java/io/airlift/compress/v3/lz4/Lz4JavaCompressor.java, src/main/java/io/airlift/compress/v3/lz4/Lz4RawCompressor.java, src/main/java/io/airlift/compress/v3/lzo/LzoCompressor.java, src/main/java/io/airlift/compress/v3/lzo/LzoRawCompressor.java, src/main/java/io/airlift/compress/v3/snappy/SnappyJavaCompressor.java, src/main/java/io/airlift/compress/v3/snappy/SnappyRawCompressor.java, src/main/java/io/airlift/compress/v3/zstd/CompressionContext.java, src/main/java/io/airlift/compress/v3/zstd/CompressionParameters.java
=> Add retained size to compressor

src/main/java/io/airlift/compress/v3/zstd/ZstdNative.java
`ZSTD_isError()` can be used to validate many output values of many methods, and is called out for those methods in the [manual](http://facebook.github.io/zstd/zstd_manual.html). It is not called out as being usable to validate the output of `ZSTD_getFrameContentSize` in that manual, and the method itself has valid negative returns for content size unknown.
=> Remove is_error invokation on function return with valid negative values

.github/workflows/main.yml, src/main/java/io/airlift/compress/v3/lz4/Lz4Compressor.java, src/main/java/io/airlift/compress/v3/lz4/Lz4Native.java, src/main/java/io/airlift/compress/v3/lz4/Lz4NativeCompressor.java, src/main/java/io/airlift/compress/v3/zstd/ZstdCompressor.java, src/test/java/io/airlift/compress/v3/lz4/TestLz4NativeFastest.java, src/test/java/io/airlift/compress/v3/zstd/TestZstdFast.java, src/test/java/io/airlift/compress/v3/zstd/TestZstdHigh.java
We want to use highest LZ4 acceleration level for page exchange compression which is a good tradeoff between CPU usage and compression ratio
=> Expose acceleration for native LZ4 and compression level for native Zstd
